---
- name: Ensure Apache is installed
  apt: name=apache2 state=present

- name: Start Apache
  service: name=apache2 state=started enabled=yes

- name: Deploy configuration file
  template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf
  notify:
  - Restart Apache

- name: Copy site files
  template: src=index.html.j2 dest={{ doc_root }}/index2.html

